# 引入numpy

In [58]:
#注意默认都会给numpy包设置别名为np
import numpy as np

# array创建数组：

In [59]:
#array()函数，括号内可以是列表、元组、数组、迭代对象、生成器等
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [60]:
#元组
a=np.array((1,2,3,4,5))
#数组
np.array(a)

array([1, 2, 3, 4, 5])

In [61]:
#迭代对象
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
#生成器
np.array([i**2 for i in range(10)])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## 创建10以内的偶数的数组

In [63]:
# np.array(range(2,11,2))
np.array([i for i in range(10) if i%2==0 and i!=0])

array([2, 4, 6, 8])

In [64]:
#列表中元素类型不相同
np.array([1,1.5,3,4.5,'5'])

array(['1', '1.5', '3', '4.5', '5'], dtype='<U32')

In [65]:
ar1=np.array(range(10))#整型
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
ar2=np.array([1,2,3.14,4,5])
ar2

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [67]:
ar3=np.array([[1,2,3],('a','b','c')])#二维数组：嵌套序列（列表，元组均可）
ar3

array([['1', '2', '3'],
       ['a', 'b', 'c']], dtype='<U11')

In [68]:
#注意嵌套序列数量不一会怎么样
ar4=np.array([[1,2,3],('a','b','c','d')])
ar4

C:\Users\72997\AppData\Local\Temp\ipykernel_2072\3908859564.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar4=np.array([[1,2,3],('a','b','c','d')])


array([list([1, 2, 3]), ('a', 'b', 'c', 'd')], dtype=object)

In [69]:
ar4.ndim#列数

1

In [70]:
ar4.shape#行数

(2,)

### 1.设置dtype参数，默认自动识别

In [71]:
a=np.array([1,2,3,4,5])
print(a)
#设置数组元素类型
has_dtype_a=np.array([1,2,3,4,5],dtype='float')
has_dtype_a

[1 2 3 4 5]


array([1., 2., 3., 4., 5.])

## 将浮点型的数据转换成整型只保留整数

In [72]:
has_dtype_a=np.array([1.1,2.2,3.3,4.4,5.8],dtype='int')
has_dtype_a

array([1, 2, 3, 4, 5])

## 2、设置copy参数，默认为true

In [73]:
a=np.array([1,2,3,4,5])
#定义b，复制a
b=np.array(a)
#输出a和b的id
print('a:',id(a),' b:',id(b))
print('以上看出a和b的内存地址')

a: 2771681094896  b: 2771681093840
以上看出a和b的内存地址


In [74]:
#当修改b的元素时，a不会发生变化
b[0]=10
print('a:',a,' b:',b)
print('='*10)

a: [1 2 3 4 5]  b: [10  2  3  4  5]


In [75]:
a=np.array([1,2,3,4,5])
#定义b，当设置copy参数为Fasle时，不会创建副本，
#两个变量会指向相同的内容地址，没有创建新的对象
b=np.array(a,copy=False)
#输出a和b的id
print('a:',id(a),' b:',id(b))
print('以上看出a和b的内存地址')
#由于a和b指向的时相同的内存地址，因此当修改b的元素时，a会发生变化
b[0]=10
print('a:',a,' b:',b)

a: 2771681161840  b: 2771681161840
以上看出a和b的内存地址
a: [10  2  3  4  5]  b: [10  2  3  4  5]


## 3、ndmin 用于指定数组的维度

a=np.array([1,2,3])
print(a)
a=np.array([1,2,3],ndmin=2)
a.ndim

#### 4、subok参数，类型为bool值，默认为False。为Ture,使用object的内部数据类型;False：使用object数组的数据类型

In [76]:
#创建一个矩阵
a=np.mat([1,2,3,4])
#输出为矩阵类型
print(type(a))
#既要复制一份副本，又要保持原类型
at=np.array(a,subok=True)
af=np.array(a)#默认为False
print('at,subok为Ture：',type(at))
print('af,subok为Ture：',type(af))
print(id(at),id(a))

<class 'numpy.matrix'>
at,subok为Ture： <class 'numpy.matrix'>
af,subok为Ture： <class 'numpy.ndarray'>
2771698107328 2771698107440


### 书写代码时需要注意的内容：

In [77]:
#定义个数组
a=np.array([2,4,3,1])
#在定义b时，如果想复制a的几种方案：
#1.使用np.array()
b=np.array(a)
print('b=np.array(a)',id(b),id(a))
#2.使用copy()
c=a.copy()
print('c=a.copy()',id(c),id(a))
#注意不能直接使用=号复制，直接使用=号，会使2个变量指向相同的内存地址
d=a
#修改d也会相应的修改a
print('d=a:',id(d),id(a))

b=np.array(a) 2771681162512 2771681163184
c=a.copy() 2771681161840 2771681163184
d=a: 2771681163184 2771681163184


In [78]:
#1.创建一个一维数组
a=np.array([2,4,3,1])
a

array([2, 4, 3, 1])

In [79]:
#2.创建一个二维数组
b=np.array([[2,4,3,1],[1,2,3,4]])
b


array([[2, 4, 3, 1],
       [1, 2, 3, 4]])

In [80]:
np.zeros(shape=(3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
#3.创建一个嵌套数组
c=np.array([[2,4,3,1],[1,2,3,4,5]])
c


C:\Users\72997\AppData\Local\Temp\ipykernel_2072\1719711306.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[2,4,3,1],[1,2,3,4,5]])


array([list([2, 4, 3, 1]), list([1, 2, 3, 4, 5])], dtype=object)

In [82]:
d=np.array([[2,4,3,1],('a','b','c')])
d

C:\Users\72997\AppData\Local\Temp\ipykernel_2072\3434928082.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[2,4,3,1],('a','b','c')])


array([list([2, 4, 3, 1]), ('a', 'b', 'c')], dtype=object)

In [83]:
#4.测试数组a，将数组赋值给b，修改b中的一个元素，查看a是否变化,如果想让b变化不影响a，应用copy()方法或者np.array()方法
a=np.array([2,4,3,1])
b=a
b[0]=1
a



array([1, 4, 3, 1])

In [84]:
c=np.array(a)
c[1]=2
a

array([1, 4, 3, 1])

In [85]:
d=a.copy()
d[2]=1
a

array([1, 4, 3, 1])

In [86]:
a=np.arange(0,200+1,3)
a

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198])

In [87]:
a=np.arange(0,200+1,3)
len(a)

67

In [88]:
#以下实例用到三个参数，设置起始点为1，终止点为10，数列个数为10
a=np.linspace(1,10,10)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [89]:
#num=5时，生成的数组长度为5，生成的数组包含了起点1和终点4，且前后两个元素的间隔相等
np.linspace(1, 4, num=5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [90]:
#设置参数endpoint为False时，不包含终止值
ar1=np.linspace(2.0,3.0,num=5,endpoint=False)
ar1

array([2. , 2.2, 2.4, 2.6, 2.8])

In [91]:
#设置参数retstep显示计算后的步长
ar2=np.linspace(2.0,3.0,num=5,retstep=True)
ar2

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [92]:
#设置参数retstep显示计算后的步长
ar3=np.linspace(2.0,3.0,num=5,retstep=True,endpoint=False)
ar3

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

# 等比数列
### 返回在间隔[开始，停止]上计算的num个均匀间隔的样本。数组是一个等比数列构成
### np.logspace(start,stop,num=50,endpoint=True,base(对数log的底数)=10.0,dtype=None)

In [93]:
#我们先使用前三个参数，将[1，5]均匀分成3个数，得到[1，3，5]
#然后利用第四个参数base=2（默认是10）使用指数函数可以得到最终输出结果[2^1,2^3,2^5]
a=np.logspace(1,5,3,base=2)
a

array([ 2.,  8., 32.])

In [94]:
a=np.logspace(0,9,10,base=2)
a

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [95]:
a=np.linspace(10000,300000,num=30)
print(a)
sum=0
for i in a:
    sum=sum+i
sum

[ 10000.  20000.  30000.  40000.  50000.  60000.  70000.  80000.  90000.
 100000. 110000. 120000. 130000. 140000. 150000. 160000. 170000. 180000.
 190000. 200000. 210000. 220000. 230000. 240000. 250000. 260000. 270000.
 280000. 290000. 300000.]


4650000.0

In [96]:
b=np.logspace(0,29,30,base=2)
print(b)
sum=0
for i in b:
    sum=sum+(i/100)
sum

[1.00000000e+00 2.00000000e+00 4.00000000e+00 8.00000000e+00
 1.60000000e+01 3.20000000e+01 6.40000000e+01 1.28000000e+02
 2.56000000e+02 5.12000000e+02 1.02400000e+03 2.04800000e+03
 4.09600000e+03 8.19200000e+03 1.63840000e+04 3.27680000e+04
 6.55360000e+04 1.31072000e+05 2.62144000e+05 5.24288000e+05
 1.04857600e+06 2.09715200e+06 4.19430400e+06 8.38860800e+06
 1.67772160e+07 3.35544320e+07 6.71088640e+07 1.34217728e+08
 2.68435456e+08 5.36870912e+08]


10737418.23

In [97]:
#默认为浮点数
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [98]:
#设置为整型
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [99]:
#设置元组为整型
a=np.zeros((5,),dtype='int')
print(a)

[0 0 0 0 0]


In [100]:
#2行2列的全0数组
np.zeros((2,2),dtype='int')
# print(np.zeros((2,2),dtype='int'))

array([[0, 0],
       [0, 0]])

In [101]:
#zeros_like返回具有与给定数组相同的形状和类型的零数组
ar1=np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
np.zeros_like(ar1)

array([[0, 0, 0],
       [0, 0, 0]])

## 全等数组

以下3个函数创建的数组，所有数组元素均相等

- `np.zeros()`: 生成一个全为0的一维或多维数组。
- `np.ones()`: 生成一个全为1的一维或多维数组。
- `np.full()`: 生成一个元素全部相等的一维或多维数组。

### np.zeros()

:book:[官方文档](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

```python
numpy.zeros(shape, ...)
```

生成一个全为0的数组，使用频率也是很高的一个函数

In [103]:
a=np.zeros(shape=4)
print(a.shape)

(4,)


In [104]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a.shape)

(2, 4)


In [105]:
a=np.array([[
             [1,2,3,4],
             [1,2,3,4]
            ],
            [
             [1,2,3,4],
             [1,2,3,4]]
            ])
print(a.shape)

(2, 2, 4)


### 调整维度reshape
#### 返回调整维度后的副本，而不改变原ndarray

In [106]:
a=np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 调整维度 resize
### numpy.resize(a,new_shape)如果新数组大于原数组，则新数组将填充a的重复副本
#### 请注意，此行为与a.resize(new_shape)不同，后者用零而不是重复的a填充

In [107]:
#a为2行2列
a=np.array([[0,1],[2,3]])
#一a 为原数组创建2行3列的新数组
b_2_3=np.resize(a,(2,3))
b_2_3

array([[0, 1, 2],
       [3, 0, 1]])

In [108]:
a.resize((3,4),refcheck=False)
a

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 2.ndarray.ndim
#### 返回数组的维度（秩）：轴的数量，或者维度的数量，是一个标量，一维数组的秩为1，二维数组的秩为2

In [109]:
a=np.array([0,1,2,3,4,5])
b=a.reshape((2,3))
c=np.array([[
             [1,2,3,4],
             [1,2,3,4]
            ],
            [
             [1,2,3,4],
             [1,2,3,4]]
            ])
print('a:',a.ndim)
print('b:',b.ndim)
print('c:',c.ndim)

a: 1
b: 2
c: 3


## 3.ndarray.size
### 数组元素的总个数，相当于.shape中n*m的值

In [110]:
a=np.array([0,1,2,3,4,5])
print('a的size=',a.size)
b=np.array([[0,1,2],[3,4,5]])
print('b的size=',b.size)

a的size= 6
b的size= 6


In [111]:
print(len(a))
print(len(b))

6
2
