In [205]:
#注意默认都会给numpy包设置别名为np
import numpy as np

In [206]:
ar1=np.arange(10)
print(ar1)
ar1

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
#从索引2开始到索引7停止，间隔为2
ar2=ar1[2:7:2]
ar2

array([2, 4, 6])

## 冒号的解释：如果只防止一个参数
##### 如[2]，将返回与该索引相对应的单个元素。
##### 如[2:]，表示从该索引开始以后的所有项都将被提取。
##### 如果使用了两个参数，如[2:7]，那么则提取两个索引（不包括停止索引）之间的项。
##### 如[2:]，表示不限制开始但是限制结束。

# 二维数组
### 同样适用上述索引提取方法

In [208]:
#定义4行5列的数据
ar4_5=np.arange(20).reshape(4,5)

ar4_5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [209]:
#返回ar4_5的秩（几维）
ar4_5.ndim

2

In [210]:
#切片为下一维度的一个元素，所以是一维数组
print(ar4_5[3])
ar4_5[3]


[15 16 17 18 19]


array([15, 16, 17, 18, 19])

In [211]:
#二次索引取得，一维数组中的元素
ar4_5[2][2]

12

In [212]:
ar4_5[2:]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 注意：切片还可以使用省略号“...”,如果在行位置使用省略号，那么返回值将包含所有行元素，反之，则包含所有列元素

In [213]:
#需要取得第二列数据
ar4_5[...,1]

array([ 1,  6, 11, 16])

In [214]:
#返回第二列以及后面的所有项
print(ar4_5[...,1:])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [215]:
#返回2行3列的数据
ar4_5[1,2]==ar4_5[1][2]
ar4_5[1,2]

7

In [216]:
#返回的是所有行中的第二行数据
ar4_5[...][1]==ar4_5[1]

array([ True,  True,  True,  True,  True])

# 索引的高级操作
### 在NumPy中还可以使用高级索引方式，比如整数数组索引、布尔索引

## 1.整数数组索引

In [217]:
#创建二维数组
x=np.array([
          [1,2],
          [3,4],
          [5,6]
         ])
#[0,1,2] 代表行索引;[0,1,0]代表列索引 即(0,0)、(1,1)和(2,0)
y=x[[0,1,2],[0,1,0]]
#y分别获取x中的(0,0)、(1,1)和(2,0)的数据
y

array([1, 4, 5])

In [218]:
a=np.array([
          [1,2,3],
          [4,5,6],
          [7,8,9]
])
#行取得2行和3行，列取得2列和3列
b=a[1:3,1:3]
#...表示所有行，1:表示从第二列开始的所有列
d=a[...,1:]
print(a)
print(b)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


# 创建一个8×8的国际象棋棋盘（黑块为0，白块为1）

In [219]:
Z=np.zeros((8,8),dtype=int)

#Z(行，列)
Z[1::2,::2]=1
print("更改前：\n"+str(Z))
Z[::2,1::2]=1
print("更改后：\n"+str(Z))

更改前：
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
更改后：
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 2.布尔数组索引
#### 当输出的结果需要经过布尔运算（如比较运算）时，此时会使用到另一种高级索引方式，即布尔数组索引。下面示例返回数组中大于6的所有元素

In [220]:
##返回所有大于6的数字组成的数组
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x[x>6]

array([ 7,  8,  9, 10, 11])

布尔索引实现的是通过一维数组中的每个元素的布尔型数值对一个与一维数组有着同样行数或列数的矩阵进行符合匹配。这种作用，其实是把一维数组中布尔值为True的相应行或列给抽取了出来
         （注意：一维数组的长度必须和想要切片的维度或轴的长度一致）

In [221]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x[(x%2)!=0]=-1
x

array([[ 0, -1,  2],
       [-1,  4, -1],
       [ 6, -1,  8],
       [-1, 10, -1]])

筛选出指定区间内数据
- & 和
- |  或

In [222]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
#以上x中大于4并且小于9的数据
x[(x>4)&(x<9)]

array([5, 6, 7, 8])

In [223]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
#以上x中小于4或者大于9的数据
x[(x<4)|(x>9)]

array([ 0,  1,  2,  3, 10, 11])

True和False的形式表示需要和不需要的数据

In [224]:
#创建3*4的数组
a3_4=np.arange(12).reshape((3,4))
a3_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [225]:
#行变量 存在3个元素
row1=np.array([False,True,True])
#列变量 存在4个元素
column1=np.array([True,False,True,False])

In [226]:
#a3_4是三行，做切片时也提供3个元素的数组，轴的长度一致
a3_4[row1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [227]:
a3_4[:,column1]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [228]:
a3_4[row1,column1]

array([ 4, 10])

是因为所选索引形状不匹配：索引数组无法与该形状一起广播。当访问numpy多为数组时，用于索引的数组需要具有相同的形状（行和列）。numpy将有可能去广播，所以，若要为了实现不同维度的选择，可分两部对数组进行选择。
1.例如我需要选择第一行和最后一行的第1，3，4列时，先选择行，再选择列。
2.先读取数组a3_4的第一行和最后一行，保存到temp，然后再筛选相应的列即可

In [229]:
a3_4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [230]:
#a3_4[[0,-1],[0,2,3]]#这样时错误的

In [231]:
#选择第一行和最后一行的第1,3,4列，操作步骤
#第一步:先选行
temp=a3_4[[0,-1],:]
temp

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [232]:
#第二步:再选择列
temp[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

In [233]:
#合并一条
a3_4[[0,-1],:][:,[0,2,3]]

array([[ 0,  2,  3],
       [ 8, 10, 11]])

In [234]:
#创建一个0-9的2*5数组ar,筛选出元素值大于5的值并生成新的数组
ar=np.arange(0,10,1).reshape(2,5)
br=ar[ar>5]
br=br.reshape(2,2)
br

array([[6, 7],
       [8, 9]])

In [235]:
#创建一个2维数组10*10，使该数组边界值为1，内部值为0
cr=np.zeros((10,10),dtype=int)

cr[0,...]=1
cr[9,...]=1
cr[...,0]=1
cr[...,9]=1
cr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [236]:
#创建一个从10到49的ndarray对象，并进行倒叙复制给另一个变量
dr=np.arange(10,50).reshape(4,10)
er=dr[::-1,::-1]
er

array([[49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

In [237]:
dr=np.arange(10,50)
er=dr[::-1]
er

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [245]:
zr=np.arange(20).reshape(4,5)
zr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [246]:
temp1=zr[1,...].copy()
print(temp1)
zr[1,...]=np.array(zr[2,...])
zr[2,...]=temp1.copy()
zr

[5 6 7 8 9]


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [247]:
zr1=zr.T
zr1

array([[ 0, 10,  5, 15],
       [ 1, 11,  6, 16],
       [ 2, 12,  7, 17],
       [ 3, 13,  8, 18],
       [ 4, 14,  9, 19]])